source "http://rubygems.org"

# Main section
# TODO: why do we need all of this?
gem 'nokogiri',               '1.6.6.2'
gem 'facter',                 '2.4.4'
gem 'json',                   '1.8.3'
gem 'hiera',                  '3.0.1'
gem 'deep_merge',             '1.0.1'
gem 'rgen',                   '0.6.6'
#gem 'ruby-augeas',            '0.4.1'
gem 'ruby-shadow',            '2.2.0'
gem 'gpgme',                  '2.0.10'
gem 'highline',               '1.6.19'     # Ruby
gem 'trollop',                '2.1.2'      # ??? FIXME
gem 'hiera-eyaml',            '2.0.8'      # MIT
gem 'rack',                   '1.6.4'
gem 'unicorn',                '4.9.0'

group :centos_6 do
  #  gem 'ruby-libvirt',         '0.4.0'
end

gem 'msgpack',                '0.6.2' # Apache v2

# Puppet tools section
gem 'puppet-syntax',          '2.0.0'
gem 'sensu-plugin',           '1.2.0'     # This is used for check_aws_events
gem 'puppet-lint',            '~> 1.1.0'  # MIT
gem 'serverspec',             '2.24.1'     # MIT
gem 'r10k',                   '1.4.1'

# AWS section
gem 'unf',                    '0.1.3'
gem 'aws-sdk',                '1.55.0'
gem 'aws-sdk-resources',      '2.0.29', :require => false
gem 'retries',                '0.0.5', :require => false
gem 'fog',                    '1.28.0'
